services:
  postgres:
    image: postgres:16
    env_file:
      - .env.development
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env.development
    ports:
      - '5050:80'
volumes:
  postgres_data: {}
